version: '2'

networks:
  app-tier:
    driver: bridge

services:
  myscore:
    image: my_score_image
    container_name: myscore
    ports:
      - 8777:5001
        #volumes:
        # - ./Scores.txt:/app/Scores.txt       
    networks:
      - app-tier

volumes:
  myscore:
    driver: local
